version: "3.7"
services:
  chroma-db:
    image: chromadb/chroma:0.5.3
    container_name: chatbot-demo-chroma-server
    ports:
      - "38000:8000"
    #http://localhost:38000/api/v1/heartbeat

  # https://hub.docker.com/r/3x3cut0r/vector-admin
  # https://github.com/Mintplex-Labs/vector-admin/tree/master/docker
  # - to connect to chroma db, use: http://host.docker.internal:38000 (with no header/secret)
  # - Bypass initial Auth (if login errors):
  #     Email: root@vectoradmin.com
  #     Password: password
  # - delete volumes after shutting down
  vector-admin:
    container_name: chatbot-demo-vector-admin
    image: 3x3cut0r/vector-admin:latest
    restart: unless-stopped
    ports:
      - "2138:3001"
      - "3355:3355"
      - "8288:8288"
    environment: # https://github.com/Mintplex-Labs/vector-admin/blob/master/docker/.env.example
      SERVER_PORT: 3001
      DATABASE_CONNECTION_STRING: "postgresql://vectoradmin:password@postgres:5432/vectoradmin"
      JWT_SECRET: "random-string-goes-here"
      INNGEST_EVENT_KEY: "background_workers"
      INNGEST_SIGNING_KEY: "random-string-goes-here"
      INNGEST_LANDING_PAGE: "true"
    volumes:
      #   - "./.env:/app/backend/.env"
      - vector-admin-data:/app/backend/storage
      - vector-admin-hotdir:/app/document-processor/hotdir
    depends_on:
      - postgres

  # https://hub.docker.com/_/postgres
  postgres:
    container_name: chatbot-demo-vector-admin-postgres
    image: postgres:16-alpine
    restart: always
    # ports:
    #   - 5432:5432
    volumes:
      - vector-admin-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "vectoradmin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "vectoradmin"
volumes:
  vector-admin-postgres:
    name: chatbot-demo-vector-admin-postgres
  vector-admin-data:
    name: chatbot-demo-vector-admin-data
  vector-admin-hotdir:
    name: chatbot-demo-vector-admin-hotdir
