#See https://aka.ms/customizecontainer to learn how to customize your debug container and how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM postgres:14
WORKDIR /src
COPY /auto-sql-scripts/ /docker-entrypoint-initdb.d/
