version: "3.7"
services:
  main-db:
    build:
      context: ./
      dockerfile: ./DockerFile
    image: chatbot-demo-main-db-image
    environment:
      - POSTGRES_PASSWORD=test
    container_name: chatbot-demo-main-db
    ports:
      - "35432:5432"
